---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.12.1 include nuovi miglioramenti. 
---
= Novità di Cloud Volumes ONTAP 9.12.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.1 include nuovi miglioramenti.

Ulteriori funzionalità e miglioramenti sono stati introdotti anche nelle ultime versioni di BlueXP (in precedenza Cloud Manager). Vedere https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Note di rilascio di BlueXP"^] per ulteriori informazioni.



== 9.12.1 P8 (8 dicembre 2023)

La patch 9.12.1 P8 è ora disponibile per Cloud Volumes ONTAP per tutti i cloud provider. BlueXP richiederà di aggiornare i sistemi esistenti a questa versione di patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.12.1P8["Visualizza l'elenco dei bug corretti nella patch P8"^] (Accesso al NetApp Support Site richiesto).



== 9.12.1 GA (9 febbraio 2023)

La release General Availability (GA) di Cloud Volumes ONTAP 9.12.1 è ora disponibile in AWS, Azure e Google Cloud. La release GA include correzioni di bug.



== 9.12.1 RC1 (8 dicembre 2022)

Cloud Volumes ONTAP 9.12.1 Release Candidate 1 è ora disponibile in AWS, Azure e Google Cloud. Questa versione include le seguenti nuove funzioni e miglioramenti.



=== Licenza ONTAP S3 in GCP

Una licenza ONTAP S3 è ora inclusa nei sistemi Cloud Volumes ONTAP nuovi ed esistenti che eseguono la versione 9.12.1 o successiva nella piattaforma Google Cloud.

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["Scopri come configurare e gestire i servizi di storage a oggetti S3 in ONTAP"^]



=== Supporto NVMe-TCP in Cloud Volumes ONTAP

NVMe-TCP è supportato per i provider cloud se si utilizza Cloud Volumes ONTAP versione 9.12.1 o successiva. BlueXP non fornisce alcuna funzionalità di gestione per NVMe-TCP.

Per ulteriori informazioni sulla configurazione di NVMe tramite ONTAP, vedere link:https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["Configurare una VM di storage per NVMe"^].



=== Ha Azure in una singola zona di disponibilità con dischi gestiti condivisi

È ora possibile distribuire una configurazione ha Cloud Volumes ONTAP utilizzando lo storage locale ridondante (LRS, Local Redundant Storage) di Microsoft Azure su dischi gestiti condivisi. Lo storage locale ridondante replica i dati tre volte all'interno di un singolo data center nella stessa area.

Per ulteriori informazioni sui componenti e sull'architettura della configurazione ha, vedere link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html["Coppie ad alta disponibilità in Azure"^].

Quando implementi una nuova coppia ha in Azure in una singola zona di disponibilità, utilizzerai i dischi gestiti condivisi LRS piuttosto che i BLOB di pagina per lo storage. Non è stata apportata alcuna modifica alla procedura guidata ambiente di lavoro. Per utilizzare questa nuova configurazione, è sufficiente scegliere una zona di disponibilità singola. Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-otc-azure.html["Lancio di una coppia Cloud Volumes ONTAP ha in Azure"^].



=== Ha Azure in più zone di disponibilità con dischi gestiti condivisi

Ora puoi implementare una configurazione ha Cloud Volumes ONTAP utilizzando più zone di disponibilità Azure all'interno di una regione. La nuova configurazione protegge dai guasti del data center e mantiene la disponibilità applicativa grazie all'utilizzo dei dischi gestiti condivisi ZRS (Zone-Redundant Storage) di Azure. Questa funzione è attualmente disponibile solo nelle regioni degli Stati Uniti occidentali 2, Europa occidentale, Europa settentrionale e Francia centrale.

Per ulteriori informazioni sui componenti e sull'architettura della configurazione ha, vedere link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html["Coppie ad alta disponibilità in Azure"^].

Per utilizzare questa nuova configurazione, vedere link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-otc-azure.html["Lancio di una coppia Cloud Volumes ONTAP ha in Azure"^].

Per ulteriori informazioni sullo storage ridondante a zone per dischi gestiti, fare riferimento a. link:https://learn.microsoft.com/en-us/azure/virtual-machines/disks-redundancy#zone-redundant-storage-for-managed-disks["Documentazione di Microsoft Azure."]



== Note sull'aggiornamento

Leggi queste note per ulteriori informazioni sull'aggiornamento a questa release.



=== Come eseguire l'upgrade

Gli aggiornamenti di Cloud Volumes ONTAP devono essere completati da BlueXP. Non aggiornare Cloud Volumes ONTAP utilizzando Gestione di sistema o l'interfaccia CLI. In questo modo si può influire sulla stabilità del sistema.

http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Scopri come eseguire l'aggiornamento quando BlueXP ti notifica"^].



=== Percorso di upgrade supportato

È possibile eseguire l'aggiornamento a Cloud Volumes ONTAP 9.12.1 dalle versioni 9.12.0 e 9.11.1. BlueXP richiederà di aggiornare i sistemi Cloud Volumes ONTAP idonei a questa versione.



=== Versione richiesta del connettore

Il connettore BlueXP deve eseguire la versione 3.9.24 o successiva per implementare nuovi sistemi Cloud Volumes ONTAP 9.12.1 e per aggiornare i sistemi esistenti alla versione 9.12.1.


TIP: Gli aggiornamenti automatici del connettore sono attivati per impostazione predefinita, pertanto dovrebbe essere in esecuzione la versione più recente.



=== Downtime

* L'aggiornamento di un sistema a nodo singolo porta il sistema offline per un massimo di 25 minuti, durante i quali l'i/o viene interrotto.
* L'aggiornamento di una coppia ha è senza interruzioni e l'i/o è ininterrotto. Durante questo processo di aggiornamento senza interruzioni, ogni nodo viene aggiornato in tandem per continuare a fornire i/o ai client.




=== Upgrade in AWS con tipi di istanze C4, M4 e R4 EC2

In AWS, i tipi di istanze C4, M4 e R4 EC2 non sono più supportati con le nuove implementazioni di Cloud Volumes ONTAP. Se si dispone di un sistema in esecuzione su un tipo di istanza c4, m4 o r4, è necessario passare a un tipo di istanza nella famiglia di istanze c5, m5 o r5. Se non è possibile modificare il tipo di istanza, è necessario abilitare la rete avanzata prima di eseguire l'aggiornamento.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["Scopri come eseguire l'upgrade in AWS con i tipi di istanza C4, M4 e R4 EC2"^].
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Scopri come modificare il tipo di istanza EC2 per Cloud Volumes ONTAP"^].

Fare riferimento a. link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Supporto NetApp"^] per ulteriori informazioni sulla fine della disponibilità e sul supporto per questi tipi di istanze.
